[project]
name = "renogy-ble"
version = "0.2.1"
description = "A library for parsing Renogy BLE data"
readme = "README.md"
requires-python = '>=3.11'
dependencies = []
authors = [
    {name = "Mitchell Carlson", email = "mitchell.carlson.pro@gmail.com"}
]
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[project.urls]
"Homepage" = "https://github.com/IAmTheMitchell/renogy-ble"
"Bug Tracker" = "https://github.com/IAmTheMitchell/renogy-ble/issues"
"Changelog" = "https://github.com/IAmTheMitchell/renogy-ble/blob/main/CHANGELOG.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.semantic_release]
branch = "main"
version_toml = ["pyproject.toml:project.version"]
